import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CategoryCard from "../components/CategoryCard";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Res and Wonder</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.container}>
        <div className={styles.small}>
          <CategoryCard
            image="/image/clothing-and-shoes.jpeg"
            name="Clothing"
          />
          <CategoryCard image="/image/home-and-living.jpeg" name="Home" />
          <CategoryCard image="/image/eco-friendly.jpeg" name="Self-care" />
          <CategoryCard
            image="https://imgur.com/qb6IW1f.png"
            name="Eco-friendly"
          />
        </div>
      </main>
    </div>
  );
}
